name: 'ncu-upgrade'
description: 'Use NCU to perform upgrades.'
outputs:
  success:
    description: 'Did it succeed?'
  upgraded:
    description: 'Whether dependencies were upgraded'
  upgrades:
    description: 'Packages that were upgraded, if any'
runs:
  using: 'node24'
  main: 'dist/index.js'